# Databricks notebook source
env = "dev"
catalog = "workspace"
base_path = "dbfs:/FileStore/tvmaze"

# COMMAND ----------

# DBTITLE 1,config
tvmaze_config = {
    "shows": {
        "source_api_url": "https://api.tvmaze.com/shows",
        "entity_name": "shows",
        "load_type": "full",
        "write_mode": "overwrite",
        "schema_evolution": "Y",
        "file_format": "json",
        "bronze_key_ids": "id",
        "silver_key_ids": "id",
        "gold_key_ids": "show_id",
        "bronze_table_name": "b_shows",
        "silver_table_name": "s_shows",
        "gold_table_name": "dim_shows",
        "bronze_schema_name": f"{env}_tvmaze_bronze",
        "silver_schema_name": f"{env}_tvmaze_silver",
        "gold_schema_name": f"{env}_tvmaze_gold",
        "bronze_partition_col": [],
        "silver_partition_col": ["partition_year","partition_month","partition_day"],
        "gold_partition_col": ["partition_year","partition_month","partition_day"],
        "audit_columns": ["created_date"],
        "cdc_column": "updated",
        "bronze_key_column": [],
        "cols_to_encrypt_bronze": [],
        "cols_to_encrypt_silver": []
    },
    "episodes": {
        "source_api_url": "https://api.tvmaze.com/shows/{}/episodes",
        "entity_name": "episodes",
        "load_type": "full",
        "write_mode": "overwrite",
        "schema_evolution": "Y",
        "file_format": "json",
        "bronze_key_ids": "id",
        "silver_key_ids": "episode_id",
        "gold_key_ids": "episode_id",
        "cdc_column": "",
        "bronze_table_name": "b_episodes",
        "silver_table_name": "s_episodes",
        "gold_table_name": "fact_episodes",
        "bronze_schema_name": f"{env}_tvmaze_bronze",
        "silver_schema_name": f"{env}_tvmaze_silver",
        "gold_schema_name": f"{env}_tvmaze_gold",
        "bronze_partition_col": [],
        "silver_partition_col": ["partition_year","partition_month","partition_day"],
        "gold_partition_col": ["partition_year","partition_month","partition_day"],
        "audit_columns": ["created_date"],
        "bronze_key_column": [],
        "cols_to_encrypt_bronze": [],
        "cols_to_encrypt_silver": []
    },
    "cast": {
        "source_api_url": "https://api.tvmaze.com/shows/{}/cast",
        "entity_name": "cast",
        "load_type": "full",
        "write_mode": "overwrite",
        "schema_evolution": "Y",
        "file_format": "json",
        "bronze_key_ids": "show_id",
        "silver_key_ids": "person_id",
        "gold_key_ids": "person_id",
        "cdc_column": "person_updated",
        "bronze_table_name": "b_cast",
        "silver_table_name": "s_cast",
        "gold_table_name": "dim_cast",
        "bronze_schema_name": f"{env}_tvmaze_bronze",
        "silver_schema_name": f"{env}_tvmaze_silver",
        "gold_schema_name": f"{env}_tvmaze_gold",
        "bronze_partition_col": [],
        "silver_partition_col": ["partition_year","partition_month","partition_day"],
        "gold_partition_col": ["partition_year","partition_month","partition_day"],
        "audit_columns": ["created_date"],
        "bronze_key_column": [],
        "cols_to_encrypt_bronze": [],
        "cols_to_encrypt_silver": []
    },
    "fact_show_data": {
        "entity_name": "fact_show_data",
        "load_type": "incremental",
        "write_mode": "append",
        "schema_evolution": "Y",
        "silver_key_ids": "show_id",
        "silver_table_name": "fact_show_data",
        "silver_schema_name": f"{env}_tvmaze_silver",
        "silver_partition_col": [],
        "audit_columns": ["dw_updated_timestamp","dw_updated_by"],
        "cdc_column": "show_id",
        "silver_key_column": ["show_id","episode_id","person_id"],
        "cols_to_encrypt_silver": [],
        "cluster_columns": ["show_id","episode_id"],
    },
    "show_analytics": {
        "entity_name": "show_analytics",
        "load_type": "full",
        "write_mode": "overwrite",
        "schema_evolution": "Y",
        "silver_schema_name": f"{env}_tvmaze_silver",
        "silver_table_name": "fact_show_data",
        "gold_schema_name": f"{env}_tvmaze_gold",
        "gold_tables": {
            "episodes_per_season": "g_episodes_per_season",
            "avg_runtime_per_show": "g_avg_runtime_per_show",
            "top_cast_members": "g_top_cast_members",
            "common_genres": "g_common_genres"
        },
        "gold_partition_col": [],
        "gold_key_ids": [],
        "cluster_columns": []
    }
}